{{- if .Values.workspaceBuilder.enabled -}}
{{ if not .Values.workspaceBuilder.workspaceInfo.useExistingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.workspaceBuilder.workspaceInfo.configMap.name }}
data:
  workspaceInfo.yaml: | 
    workspaceName: {{ .Values.workspaceName }}
    {{- .Values.workspaceBuilder.workspaceInfo.configMap.data | toYaml | nindent 4 }}
{{ end }}
{{ end }}