{{- $wb := include "runwhen-local.resolveWorkspaceBuilder" . | fromYaml -}}
{{- if $wb.enabled -}}
{{ if not $wb.workspaceInfo.useExistingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $wb.workspaceInfo.configMap.name }}
data:
  workspaceInfo.yaml: | 
    workspaceName: {{ .Values.workspaceName }}
    {{- $wb.workspaceInfo.configMap.data | toYaml | nindent 4 }}
{{ end }}
{{ end }}