{{- if .Values.workspaceBuilder.enabled -}}
{{- if .Values.workspaceBuilder.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}
  labels:
    {{- include "runwhen-local.labels" . | nindent 4 }}
  {{- with .Values.workspaceBuilder.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    kubernetes.io/service-account.token-expiration: "31536000"  # 1 year in seconds
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}-token
  annotations:
    kubernetes.io/service-account.name: {{ .Values.workspaceBuilder.serviceAccount.name }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}-sa-local-view
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "events", "configmaps", "services", "replicationcontrollers", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}-sa-local-view-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}-sa-local-view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.workspaceBuilder.serviceAccount.name }}
    namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}-sa-secret-manage
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}-sa-secret-manage-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.workspaceBuilder.serviceAccount.name }}-sa-secret-manage
subjects:
  - kind: ServiceAccount
    name: {{ .Values.workspaceBuilder.serviceAccount.name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}