{{- if .Values.workspaceBuilder.enabled -}}
{{- if .Values.workspaceBuilder.serviceAccountRoles.clusterRoleView.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.workspaceBuilder.serviceAccount.name }}-view-crb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.workspaceBuilder.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}