{{- if .Values.workspaceBuilder.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "runwhen-local.workspaceBuilderFullname" . }}
  labels:
    {{- include "runwhen-local.labels" . | nindent 4 }}
spec:
  type: {{ .Values.workspaceBuilder.service.type }}
  ports:
    - name: mkdocs
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: django
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    {{- include "runwhen-local.selectorLabels" . | nindent 4 }}
{{- end }}
