{{- $wb := include "runwhen-local.resolveWorkspaceBuilder" . | fromYaml -}}
{{- if $wb.enabled -}}
{{- if $wb.serviceAccountRoles.namespaceRole.enabled -}}
{{- $releaseNamespace := list .Release.Namespace }}
{{- $allNamespaces := concat $releaseNamespace $wb.serviceAccountRoles.namespaceRole.namespaces }}
{{- range $ns := $allNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $ns }}
  name: {{ include "runwhen-local.serviceAccountName" $ }}-namespace-view
rules:
{{ toYaml $wb.serviceAccountRoles.namespaceRole.rules | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runwhen-local.serviceAccountName" $ }}-view-rb
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runwhen-local.serviceAccountName" $ }}-namespace-view
subjects:
  - kind: ServiceAccount
    name: {{ include "runwhen-local.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}