{{- $wb := include "runwhen-local.resolveWorkspaceBuilder" . | fromYaml -}}
{{- if $wb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runwhen-local.workspaceBuilderFullname" . }}
  labels:
    {{- include "runwhen-local.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runwhen-local.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $wb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
          app: runwhen-local
          {{- include "runwhen-local.selectorLabels" . | nindent 10 }}
    spec:
      {{- include "runwhen-local.podSecurityContext" . | nindent 6 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $wb.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- include "runwhen-local.containerSecurityContext" . | nindent 10 }}
          image: "{{ ($wb.image.registry | default .Values.registryOverride)| default "ghcr.io" }}/{{ $wb.image.repository | default "runwhen-contrib/runwhen-local" }}:{{ $wb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $wb.image.pullPolicy }}
          env: 
          - name: TMPDIR
            value: /tmp   
          - name: AUTORUN_WORKSPACE_BUILDER_INTERVAL
            value: "{{ $wb.autoRun.discoveryInterval }}"
          - name: RW_LOCAL_TERMINAL_DISABLED
            value: "{{ $wb.terminal.disabled }}"
          - name: RW_LOCAL_UPLOAD_ENABLED
            value: "{{ $wb.autoRun.uploadEnabled }}"
          - name: RW_LOCAL_UPLOAD_MERGE_MODE
            value: "{{ $wb.autoRun.uploadMergeMode }}"
          {{- if $wb.debugLogs }}
          - name: DEBUG_LOGGING
            value: "true"
          {{- end }}
          {{- if $wb.cheatSheet.disabled }}
          - name: WB_DEBUG_SUPPRESS_CHEAT_SHEET
            value: "yes"
          {{- end }}
          {{- if $wb.discoveryKubeconfig.inClusterAuth.createKubeconfigSecret }}
          - name: RW_CREATE_KUBECONFIG_SECRET
            value: "true"
          {{- end }}
          - name: KUBERNETES_CLUSTER_NAME
            value: {{ $wb.clusterName }}
          {{- if .Values.proxy.enabled }}
          {{- with .Values.proxy.httpProxy }}
          - name: HTTP_PROXY
            value: {{ . }}
          {{- end }}
          {{- with .Values.proxy.httpsProxy }}
          - name: HTTPS_PROXY
            value: {{ . }}
          {{- end }}
          {{- with .Values.proxy.noProxy }}
          - name: NO_PROXY
            value: {{ . }}
          {{- end }}
          {{- if or .Values.proxyCA $wb.proxyCA }}
          - name: SLI_CERT_FILE
            value: "/etc/ssl/certs/ca-certificates.crt"
          - name: REQUESTS_CA_BUNDLE
            value: "/etc/ssl/certs/ca-certificates.crt"
          - name: NODE_EXTRA_CA_CERTS
            value: "/etc/ssl/certs/ca-certificates.crt"
          {{- end }}
          {{- end }}
          {{- with $wb.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: mkdocs
              containerPort: 8081
              protocol: TCP
            - name: django
              containerPort: 8000
              protocol: TCP
          {{- if $wb.livenessProbe }}
          livenessProbe:
            {{- toYaml $wb.livenessProbe | nindent 12 }}
          {{- else }}
          livenessProbe:
            tcpSocket:
              port: django
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 20
          {{- end }}
          {{- if $wb.readinessProbe }}
          readinessProbe:
            {{- toYaml $wb.readinessProbe | nindent 12 }}
          {{- else }}
          readinessProbe:
            tcpSocket:
              port: django
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          {{- end }}
          resources:
            {{- if eq .Values.platformType "EKS_Fargate" }}
            {{- toYaml $wb.resources.EKS_Fargate | nindent 12 }}
            {{- else }}
            {{- toYaml $wb.resources.default | nindent 12 }}
            {{- end }}
          volumeMounts:
          {{- with $wb.volumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if or .Values.proxy.enabled $wb.proxy }}
          {{- if or .Values.proxyCA $wb.proxyCA }}
          - name: proxy-ca
            mountPath: /etc/ssl/certs/ca-certificates.crt
            subPath: ca-certificates.crt
          {{- end }}
          {{- end }}
          - name: shared-volume
            mountPath: "/shared"
          - name: tmpdir
            mountPath: "/tmp"
          {{- if $wb.discoveryKubeconfig.secretProvided.enabled }}
          - name: kubeconfig-secret-volume
            mountPath: "/shared/kubeconfig"
            subPath: "kubeconfig"
          {{- end }}
          - name: configmap-volume
            mountPath: "/shared/workspaceInfo.yaml"
            subPath: "workspaceInfo.yaml"
          {{- if $wb.uploadInfo.secretProvided.enabled }}
          - name: upload-secret-volume
            mountPath: "/shared/uploadInfo.yaml"
            subPath: "uploadInfo.yaml"
          {{- end }}
      volumes:
      {{- with $wb.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if or .Values.proxy.enabled $wb.proxy }}
      {{- with or .Values.proxyCA $wb.proxyCA }}
      - name: proxy-ca
        {{- if .secretName }}
        secret:
          secretName: {{ .secretName }}
        {{- else if .configMapName }}
        configMap:
          name: {{.configMapName }}
        {{- end }}
          items:
          - key: {{ .key | default "ca.crt" }}
            path: ca-certificates.crt
          defaultMode: 420
      {{- end }}
      {{- end }}
      - name: shared-volume
        emptyDir: {}
      - name: tmpdir
        emptyDir: {}
      {{- if $wb.discoveryKubeconfig.secretProvided.enabled }}
      - name: kubeconfig-secret-volume
        secret:
          secretName: {{ $wb.discoveryKubeconfig.secretProvided.secretName }}
          items:
            - key: {{ $wb.discoveryKubeconfig.secretProvided.secretKey }}
              path: {{ $wb.discoveryKubeconfig.secretProvided.secretPath }}
      {{- end }}
      {{- if $wb.uploadInfo.secretProvided.enabled }}
      - name: upload-secret-volume
        secret:
          secretName: {{ $wb.uploadInfo.secretProvided.secretName }}
          items:
            - key: {{ $wb.uploadInfo.secretProvided.secretKey }}
              path: {{ $wb.uploadInfo.secretProvided.secretPath }}
      {{- end }}
      - name: configmap-volume
        configMap:
          name: {{ if $wb.workspaceInfo.useExistingConfigMap }}{{ $wb.workspaceInfo.existingConfigMapName }}{{ else }}{{ $wb.workspaceInfo.configMap.name }}{{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (eq .Values.platformArch "arm64") (not (empty .Values.tolerations)) (not (empty $wb.tolerations)) }}
      tolerations:
      {{- if eq .Values.platformArch "arm64" }}
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
      {{- end }}
      {{- with .Values.tolerations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $wb.tolerations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
{{- end }}